apiVersion: v1
kind: Template
metadata:
  name: unleash-proxy
objects:

- apiVersion: v1
  kind: Secret
  metadata:
    name: unleash-ephemeral
  type: Opaque
  data:
    CLIENT_ACCESS_TOKEN: ''

- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: unleash-proxy
  spec:
    envName: ${ENV_NAME}
    featureFlags: true
    deployments:
    - name: api
      minReplicas: ${{REPLICAS}}
      webServices:
        public:
          enabled: True
          apiPath: featureflags
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        resources:
          limits:
            cpu: 500m
            memory: ${MEMORY_LIMIT}
          requests:
            cpu: 100m
            memory: ${MEMORY_REQUEST}
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 10
        env:
          - name: UNLEASH_URL
            value: ${UNLEASH_URL}
          - name: UNLEASH_TOKEN
            valueFrom:
              secretKeyRef:
                name: ${UNLEASH_SECRET_NAME}
                key: CLIENT_ACCESS_TOKEN
          - name: API_PREFIX
            value: ${API_PREFIX}
          - name: LOG_LEVEL
            value: ${LOG_LEVEL}
          - name: UNLEASH_LOGLEVEL
            value: ${UNLEASH_LOGLEVEL}

parameters:
- description: Number of API replicas
  name: REPLICAS
  value: '1'
- descripton: Proxy image name
  name: IMAGE
  value: "quay.io/cloudservices/unleash-proxy"
- description: Proxy Image tag
  name: IMAGE_TAG
  required: true
  value: latest
- description: Clowder ENV
  name: ENV_NAME
  required: true
- description: Clowder enabled flag
  name: CLOWDER_ENABLED
  value: 'True'
- description: Memory request
  name: MEMORY_REQUEST
  value: 2Gi
- description: Memory limit
  name: MEMORY_LIMIT
  value: 4Gi
- descript: Unleash API url
  name: UNLEASH_URL
  value: ''
- description: Unleash secret name
  name: UNLEASH_SECRET_NAME
  value: unleash-ephemeral
- description: API prefix
  name: API_PREFIX
  value: /api/featureflags
- description: log level
  name: LOG_LEVEL
  value: debug
- description: unleash log level
  name: UNLEASH_LOGLEVEL
